name: native_synchronization
description: Low level synchronization primitives built on dart:ffi.
version: 0.1.0-wip
repository: https://github.com/dart-lang/native_synchronization

environment:
  sdk: ">=3.1.0-348.0.dev <4.0.0"

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.16.0
